name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # só roda deploy quando um PR for mesclado na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Build do Vite
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
